language: ruby
rvm:
- 2.5.1
jobs:
  include:
    - stage: lint
      script:
        - rubocop
        - find app/views/ -name *.haml | xargs haml --check
    - stage: test
      script:
        - bin/rails db:migrate RAILS_ENV=test
        - RAILS_ENV=test bin/rails test
